"""adicionado a coluna de icone em categorias

Revision ID: 15f5e88f00f6
Revises: ff491c3568cb
Create Date: 2026-06-10 00:00:43.533967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15f5e88f00f6'
down_revision = 'ff491c3568cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('icone')

    # ### end Alembic commands ###
