"""Adicionada coluna de despesas fixas

Revision ID: 1b5f03246ae8
Revises: 
Create Date: 2026-06-07 04:19:42.991222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b5f03246ae8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('natureza', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('natureza')
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
