"""mudança na tabela de accounts

Revision ID: ff491c3568cb
Revises: 1b5f03246ae8
Create Date: 2026-06-08 00:26:12.911902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff491c3568cb'
down_revision = '1b5f03246ae8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cor', sa.String(length=7), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_column('dia_fechamento')
        batch_op.drop_column('dia_vencimento')
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('dia_vencimento', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dia_fechamento', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.alter_column('nome',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('cor')

    # ### end Alembic commands ###
