name: Backend CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest # A máquina virtual do GitHub já vem com Docker instalado

    steps:
    - name: Clonar o código do repositório
      uses: actions/checkout@v3

    - name: Subir a infraestrutura com Docker Compose
      run: docker-compose up -d --build

    - name: Aguardar o banco de dados ficar pronto
      run: sleep 5 # Pausa de segurança para o PostgreSQL ligar completamente

    - name: Rodar os testes automatizados dentro do container
      # O parâmetro -T é obrigatório em CI/CD porque a nuvem não tem um terminal interativo
      run: docker-compose exec -T api pytest